version: "3.8"

services:
  influxdb:
    image: influxdb:1.8
    container_name: k6-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb-data:/var/lib/influxdb

volumes:
  influxdb-data:
